server-port=25570
level-name=world
level-type=flat
generate-structures=false
allow-nether=false
allow-end=false
gamemode=adventure
difficulty=normal
pvp=false
max-players=100
online-mode=false
enforce-secure-profile=false
spawn-protection=0
view-distance=10
simulation-distance=8
motd=\u00a7c\u00a7lSmash the Boss \u00a78\u2013 \u00a77Pink Horizon
